#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Jul 30 14:58:40 CST 2026
maven-metadata-aliyun.xml.error=
maven-metadata-aliyun.xml.lastUpdated=1785394720581
maven-metadata-central.xml.error=
maven-metadata-central.xml.lastUpdated=1785394720603
maven-metadata-spring-milestones.xml.error=
maven-metadata-spring-milestones.xml.lastUpdated=1785394720610
